version: "3.8"
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile

    image : "mongo:${MONGO_VERSION}"
    platform: linux/amd64
    container_name: mongodb-fynd
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
