version: "3"
services:
  # mongodb:
  #   build:
  #     context: .
  #     dockerfile: ./docker/mongodb/Dockerfile

  #   image : "mongo:${MONGO_VERSION}"
  #   # platform: linux/amd64
  #   container_name: "${CONTAINER_NAME}"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   # volumes:
  #   #   - ./database:/data/db       #persistent database
  #   ports:
  #     - 27017:27017
  #   restart: unless-stopped

  solr:
    build:
      context: .
      dockerfile: ./docker/solr/Dockerfile

    image: "solr:8.11.2"
    container_name: "local-solr"
    platform: linux/arm64/v8   # platform: osx | platform: windows/amd64 | platform: linux/arm64/v8
    ports:
     - "8985:8983"
    volumes:
      - data:/var/solr
    # command:
    #   - solr-precreate
    #   - products_v2
    # restart: unless-stopped

  solr-v1:
    build:
      context: .
      dockerfile: ./docker/solr/Dockerfile

    image: "solr:8.11.2"
    container_name: "local-solr-v2"
    ports:
     - "8983:8983"
    platform: linux/arm64/v8 
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted

volumes:
  data:
