version: "3.8"
services:
  solr:
    image: solr
    ports:
     - "8984:8983"
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - gettingstarted

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile

    image : "mongo:${MONGO_VERSION}"
    platform: linux/amd64
    container_name: "${CONTAINER_NAME}"
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - ./database:/data/db       #persistent database
    ports:
      - 27017:27017
    restart: unless-stopped
