services:
  kafka:
    build:
      context: ${PROJECT_DIR}/docker-compose/kafka
      dockerfile: Dockerfile

    image : "lensesio/fast-data-dev:latest"
    # platform: ${DOCKER_PLATFORM}      # platform: osx | platform: windows/amd64 | platform: linux/arm64/v8
    container_name: local-kafka
    environment:
      - ${PROJECT_DIR}/.env
    ports:
      - 3181:3181
      - 3040:3040
      - 7081:7081
      - 7082:7082
      - 7083:7083
      - 7092:7092
    restart: unless-stopped